apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.99.101
  ports:
  - port: 22
    name: ssh
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 443