apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps  
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster 
  loadBalancerIP: 192.168.99.101
  selector:
    app: ftps
  ports:
  - port: 20
    name: ftp-data
  - port: 21
    name: ftp-connection
  - port: 30000
    name: pftp-data-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000